---
# tasks file for vcenter-assign-tag
- name: Assign tag to vm
  community.vmware.vmware_tag_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    object_name: "{{ vm_name }}"
    object_type: VirtualMachine
    state: add
    tag_names:
      - "{{ tag_category }}:{{ tag_name }}"
  delegate_to: localhost
